name: DevSecOps Pipeline

on:
  push:
    branches:
      - vulns

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Scan Vulnerabilities
      run: npm audit --omit=dev

    - name: Static Code Analysis
      uses: returntocorp/semgrep-action@v1
